runtime: nodejs
env: flex
env_variables:
  INSTANCE_CONNECTION_NAME: api-project-713618765244:us-central1:eventmanagedb
  MY_PASS: kMF1tL1PnIMfsyAq
  MY_HOST: 35.188.24.151
  MY_USER: root
  MY_DBN: emdb 
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 0.5
beta_settings:
  cloud_sql_instances: api-project-713618765244:us-central1:eventmanagedb